create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  category text not null,
  description text not null default '',
  image_url text,
  stock integer not null default 0,
  price numeric(12,2) not null default 0,
  cost numeric(12,2) not null default 0,
  status text not null default 'In Stock',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'staff',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  supplier text not null default '',
  quantity integer not null,
  remaining_stock integer not null,
  unit_cost numeric(12,2) not null,
  purchase_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sale_no text not null unique,
  customer text not null default '',
  payment_method text not null,
  total_amount numeric(12,2) not null,
  status text not null default 'Completed',
  sale_date timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  cost_unit numeric(12,2) not null,
  line_total numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create or replace function public.record_sale(
  sale_payload jsonb
)
returns bigint
language plpgsql
security definer
as $$
declare
  v_sale_id bigint;
  v_sale_no text := 'SA-' || to_char(now(), 'YYYYMMDDHH24MISSMS');
  v_total numeric(12,2) := 0;
  v_customer text := coalesce(sale_payload->>'customer', '');
  v_payment_method text := coalesce(sale_payload->>'payment_method', 'Cash');
  v_item record;
  v_product record;
  v_needed integer;
  v_take integer;
  v_batch record;
begin
  insert into public.sales (sale_no, customer, payment_method, total_amount, status)
  values (v_sale_no, v_customer, v_payment_method, 0, 'Completed')
  returning id into v_sale_id;

  for v_item in
    select * from jsonb_to_recordset(coalesce(sale_payload->'items', '[]'::jsonb)) as x(product_id bigint, quantity integer, price numeric)
  loop
    select * into v_product
    from public.products
    where id = v_item.product_id
    for update;

    if not found then
      raise exception 'Product % not found', v_item.product_id;
    end if;

    if v_product.stock < v_item.quantity then
      raise exception 'Insufficient stock for product %', v_product.name;
    end if;

    update public.products
    set stock = stock - v_item.quantity,
        status = case
          when stock - v_item.quantity <= 0 then 'Out of Stock'
          when stock - v_item.quantity <= 15 then 'Low Stock'
          else 'In Stock'
        end,
        updated_at = now()
    where id = v_product.id;

    v_needed := v_item.quantity;

    for v_batch in
      select *
      from public.inventory_batches
      where product_id = v_product.id and remaining_stock > 0
      order by purchase_date asc, created_at asc, id asc
      for update
    loop
      exit when v_needed <= 0;
      v_take := least(v_batch.remaining_stock, v_needed);
      update public.inventory_batches
      set remaining_stock = remaining_stock - v_take
      where id = v_batch.id;
      v_needed := v_needed - v_take;
    end loop;

    insert into public.sale_items (sale_id, product_id, quantity, unit_price, cost_unit, line_total)
    values (v_sale_id, v_product.id, v_item.quantity, v_item.price, v_product.cost, v_item.quantity * v_item.price);

    v_total := v_total + (v_item.quantity * v_item.price);
  end loop;

  update public.sales
  set total_amount = v_total
  where id = v_sale_id;

  return v_sale_id;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'staff')
  )
  on conflict (id) do update
  set full_name = excluded.full_name,
      role = excluded.role,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.inventory_batches enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

create policy "authenticated read products"
on public.products
for select
to authenticated
using (true);

create policy "authenticated manage products"
on public.products
for all
to authenticated
using (true)
with check (true);

create policy "authenticated read profiles"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "authenticated manage profiles"
on public.profiles
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "authenticated read batches"
on public.inventory_batches
for select
to authenticated
using (true);

create policy "authenticated manage batches"
on public.inventory_batches
for all
to authenticated
using (true)
with check (true);

create policy "authenticated read sales"
on public.sales
for select
to authenticated
using (true);

create policy "authenticated manage sales"
on public.sales
for all
to authenticated
using (true)
with check (true);

create policy "authenticated read sale_items"
on public.sale_items
for select
to authenticated
using (true);

create policy "authenticated manage sale_items"
on public.sale_items
for all
to authenticated
using (true)
with check (true);